### ISSUE TITLE
Como utilizar a Tucuruí

### ISSUE THREAD

**Issue by caue-alves** [joseflaviojr/tucurui#1]
Olá @joseflaviojr, achei interessante a sua iniciativa de desenvolver essa linguagem textual e gostaria de a utilizar em meus projetos, mas não encontrei nenhum documento de código, apenas as licenças, sendo assim, como eu poderia realizar sua utilização, a linguagem é apenas um projeto ainda não começado ou o código fonte para download está em outro repositório? Obrigado.

**Comment by joseflaviojr** [comment]
Oi, Cauê!

Muito obrigado pela atenção dada a este projeto, realmente não existia um executável embutido. Ao seu pedido, desenvolvi dois pequenos scripts em [Groovy](https://www.groovy-lang.org/syntax.html) para converter arquivos Tucuruí para HTML ou XML. Faça [download completo](https://github.com/joseflaviojr/tucurui/archive/master.zip)/clone deste projeto, que inclui um arquivo de exemplo Tucuruí ([Exemplo.tuc](https://github.com/joseflaviojr/tucurui/blob/master/Exemplo.tuc)), e siga os passos descritos no capítulo [Script em Groovy](https://github.com/joseflaviojr/tucurui#31-script-em-groovy). Para instalar a linguagem Groovy, que exige Java 8 ou superior, acesse https://groovy.apache.org/download.html

Abraços!
